### ISSUE TITLE
Regarding adding product on tesco basket by my wp website

### ISSUE THREAD

**Issue by ramji15** [onegambler/alexa-tesco-skill#6]
Hello Api Author,
How can i use that api in my wordpres site. I also want to add product on tesco basket by my site.
please help me!

**Comment by onegambler** [comment]
Hi @ramji15, this project doesn't provide APIs to add items to the tesco basket. It's an Amazon Alexa integration, to be able to add items to the Tesco groceries basket using Alexa and IFTTT.
As far as I know Tesco don't provide APIs to achieve that, yet.
